copy ..\..\bin\X64_Release\vismtv_inbuilt_rwfiles.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\release
copy ..\..\bin\X64_Release\vismtv_inbuilt_tfmapgenerator.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\release
copy ..\..\bin\X64_Release\vismtv_inbuilt_ptypeprocessing.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\release
copy ..\..\bin\X64_Release\vismtv_inbuilt_vtypeprocessing.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\release
copy ..\..\bin\X64_Release\vismtv_inbuilt_renderercpu.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\release
copy ..\..\bin\X64_Release\vismtv_inbuilt_renderergpudx.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\release
copy ..\..\bin\X64_Release\vismtv_modeling_vera.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\release
copy ..\..\bin\X64_Release\vismtv_morphfilters.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\release
copy ..\..\bin\X64_Release\vismtv_meshextraction.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\release
copy ..\..\bin\X64_Release\vismtv_geometryanalyzer.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\release
copy ..\..\bin\X64_Release\FreeImage.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\release
copy ..\..\bin\X64_Release\CommonUnits.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\release
copy ..\..\bin\X64_Release\CommonApi.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\release
copy ..\..\bin\X64_Release\CommonApi.lib E:\Projects\Project_Sources\librealsense-2.11.1\build\release
copy ..\..\bin\X64_Release\GpuManager.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\release
copy ..\..\bin\X64_Release\vismtv_dxutwrapper.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\release

copy ..\..\bin\X64_Debug\vismtv_inbuilt_rwfiles.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\debug
copy ..\..\bin\X64_Debug\vismtv_inbuilt_tfmapgenerator.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\debug
copy ..\..\bin\X64_Debug\vismtv_inbuilt_ptypeprocessing.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\debug
copy ..\..\bin\X64_Debug\vismtv_inbuilt_vtypeprocessing.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\debug
copy ..\..\bin\X64_Debug\vismtv_inbuilt_renderercpu.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\debug
copy ..\..\bin\X64_Debug\vismtv_inbuilt_renderergpudx.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\debug
copy ..\..\bin\X64_Debug\vismtv_modeling_vera.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\debug
copy ..\..\bin\X64_Debug\vismtv_morphfilters.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\debug
copy ..\..\bin\X64_Debug\vismtv_meshextraction.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\debug
copy ..\..\bin\X64_Debug\vismtv_geometryanalyzer.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\debug
copy ..\..\bin\X64_Debug\FreeImage.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\debug
copy ..\..\bin\X64_Debug\CommonUnits.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\debug
copy ..\..\bin\X64_Debug\CommonApi.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\debug
copy ..\..\bin\X64_Debug\CommonApi.lib E:\Projects\Project_Sources\librealsense-2.11.1\build\debug
copy ..\..\bin\X64_Debug\GpuManager.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\debug
copy ..\..\bin\X64_Debug\vismtv_dxutwrapper.dll E:\Projects\Project_Sources\librealsense-2.11.1\build\debug

//copy ..\..\EngineCores\CommonApi\VisMtvApi.h G:\vismotive