copy ..\..\bin\X64_Release\vismtv_inbuilt_rwfiles.dll E:\project_srcs\VisMotive\Test\x64\Release
copy ..\..\bin\X64_Release\vismtv_inbuilt_tfmapgenerator.dll E:\project_srcs\VisMotive\Test\x64\Release
copy ..\..\bin\X64_Release\vismtv_inbuilt_ptypeprocessing.dll E:\project_srcs\VisMotive\Test\x64\Release
copy ..\..\bin\X64_Release\vismtv_inbuilt_vtypeprocessing.dll E:\project_srcs\VisMotive\Test\x64\Release
copy ..\..\bin\X64_Release\vismtv_inbuilt_renderercpu.dll E:\project_srcs\VisMotive\Test\x64\Release
copy ..\..\bin\X64_Release\vismtv_inbuilt_renderergpudx.dll E:\project_srcs\VisMotive\Test\x64\Release
copy ..\..\bin\X64_Release\vismtv_modeling_vera.dll E:\project_srcs\VisMotive\Test\x64\Release
copy ..\..\bin\X64_Release\vismtv_morphfilters.dll E:\project_srcs\VisMotive\Test\x64\Release
copy ..\..\bin\X64_Release\vismtv_meshextraction.dll E:\project_srcs\VisMotive\Test\x64\Release
copy ..\..\bin\X64_Release\vismtv_geometryanalyzer.dll E:\project_srcs\VisMotive\Test\x64\Release
copy ..\..\bin\X64_Release\FreeImage.dll E:\project_srcs\VisMotive\Test\x64\Release
copy ..\..\bin\X64_Release\CommonUnits.dll E:\project_srcs\VisMotive\Test\x64\Release
copy ..\..\bin\X64_Release\CommonApi.dll E:\project_srcs\VisMotive\Test\x64\Release
copy ..\..\bin\X64_Release\GpuManager.dll E:\project_srcs\VisMotive\Test\x64\Release
copy ..\..\bin\X64_Release\vismtv_dxutwrapper.dll E:\project_srcs\VisMotive\Test\x64\Release

copy ..\..\bin\X64_Debug\vismtv_inbuilt_rwfiles.dll E:\project_srcs\VisMotive\Test\x64\Debug
copy ..\..\bin\X64_Debug\vismtv_inbuilt_tfmapgenerator.dll E:\project_srcs\VisMotive\Test\x64\Debug
copy ..\..\bin\X64_Debug\vismtv_inbuilt_ptypeprocessing.dll E:\project_srcs\VisMotive\Test\x64\Debug
copy ..\..\bin\X64_Debug\vismtv_inbuilt_vtypeprocessing.dll E:\project_srcs\VisMotive\Test\x64\Debug
copy ..\..\bin\X64_Debug\vismtv_inbuilt_renderercpu.dll E:\project_srcs\VisMotive\Test\x64\Debug
copy ..\..\bin\X64_Debug\vismtv_inbuilt_renderergpudx.dll E:\project_srcs\VisMotive\Test\x64\Debug
copy ..\..\bin\X64_Debug\vismtv_modeling_vera.dll E:\project_srcs\VisMotive\Test\x64\Debug
copy ..\..\bin\X64_Debug\vismtv_morphfilters.dll E:\project_srcs\VisMotive\Test\x64\Debug
copy ..\..\bin\X64_Debug\vismtv_meshextraction.dll E:\project_srcs\VisMotive\Test\x64\Debug
copy ..\..\bin\X64_Debug\vismtv_geometryanalyzer.dll E:\project_srcs\VisMotive\Test\x64\Debug
copy ..\..\bin\X64_Debug\FreeImage.dll E:\project_srcs\VisMotive\Test\x64\Debug
copy ..\..\bin\X64_Debug\CommonUnits.dll E:\project_srcs\VisMotive\Test\x64\Debug
copy ..\..\bin\X64_Debug\CommonApi.dll E:\project_srcs\VisMotive\Test\x64\Debug
copy ..\..\bin\X64_Debug\GpuManager.dll E:\project_srcs\VisMotive\Test\x64\Debug
copy ..\..\bin\X64_Debug\vismtv_dxutwrapper.dll E:\project_srcs\VisMotive\Test\x64\Debug